###
GET http://localhost:8080/supported-patterns

###
POST http://localhost:8080/application?framework=Python&pattern=Layered&name=LayeredTestProject&visibility=2
Content-Type: application/json
gitLabServerURL: https://gitlab.com
gitlabToken: <gitLabToken>

###
GET http://localhost:8080/survey

###
POST http://localhost:8080/evaluation
Content-Type: application/json

[]
